### ISSUE TITLE
Issue coming up while trying to add timesheets for non admin users

### ISSUE THREAD

**Issue by bvanjeelharia** [onesteinbv/ProjectManagement#25]
@Trivedi-Vacha-SerpentCS , we found an issue which comes up while trying to add timesheets for non admin users.I checked in the logs and found that the issue was ValueError: Invalid field 'product_id' on model 'hr.employee.public'.

Basically, it has to do with the hr.employee and hr.employee.public models are defined, if you check in the hr module -> models -> hr_employee.py file, you would find the lines as follows:
NB: Any field only available on the model hr.employee (i.e. not on the
    hr.employee.public model) should have `groups="hr.group_hr_user"` on its
    definition to avoid being prefetched when the user hasn't access to the
    hr.employee model. Indeed, the prefetch loads the data for all the fields
    that are available according to the group defined on them.

So, for the fields that you have added in the project_scrum_agile module -> models -> hr_employee.py file should be added to the hr.employee.public model or "hr.group_hr_user" group should be added on these fields.Please do the needful as per the requirements

**Comment by Trivedi-Vacha-SerpentCS** [comment]
@bvanjeelharia May I know Is that warning or traceback?

**Comment by bvanjeelharia** [comment]
@Trivedi-Vacha-SerpentCS  , Its a traceback. Here is the complete traceback:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
KeyError: 18

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/fields.py", line 1082, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo-server/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'hr.employee(18,).active'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 368, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/http.py", line 357, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 921, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 546, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1324, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1316, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/hr_timesheet/models/project.py", line 329, in write
    res = super(Task, self).write(values)
  File "/opt/odoo/odoo-server/addons/project/models/project.py", line 1833, in write
    result = super(Task, tasks).write(vals)
  File "/opt/odoo/odoo-server/addons/mail/models/mail_thread.py", line 323, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo/odoo-server/addons/mail/models/mail_activity_mixin.py", line 243, in write
    return super(MailActivityMixin, self).write(vals)
  File "/opt/odoo/odoo-server/addons/rating/models/rating_mixin.py", line 84, in write
    result = super(RatingMixin, self).write(values)
  File "/opt/odoo/odoo-server/odoo/models.py", line 3869, in write
    field.write(self, value)
  File "/opt/odoo/odoo-server/odoo/fields.py", line 3301, in write
    return self.write_batch([(records, value)])
  File "/opt/odoo/odoo-server/odoo/fields.py", line 3322, in write_batch
    return self.write_real(records_commands_list, create)
  File "/opt/odoo/odoo-server/odoo/fields.py", line 3498, in write_real
    flush()
  File "/opt/odoo/odoo-server/odoo/fields.py", line 3460, in flush
    comodel.create(to_create)
  File "<decorator-gen-204>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-server/addons/hr_timesheet/models/hr_timesheet.py", line 146, in create
    if any(not emp.active for emp in self.env['hr.employee'].browse(list(employee_ids))):
  File "/opt/odoo/odoo-server/addons/hr_timesheet/models/hr_timesheet.py", line 146, in <genexpr>
    if any(not emp.active for emp in self.env['hr.employee'].browse(list(employee_ids))):
  File "/opt/odoo/odoo-server/odoo/fields.py", line 1108, in __get__
    recs._fetch_field(self)
  File "/opt/odoo/odoo-server/odoo/models.py", line 3278, in _fetch_field
    self._read(fnames)
  File "/opt/odoo/odoo-server/addons/hr/models/hr_employee.py", line 170, in _read
    res = self.env['hr.employee.public'].browse(self.ids).read(fields)
  File "/opt/odoo/odoo-server/odoo/models.py", line 3218, in read
    raise ValueError("Invalid field %r on model %r" % (name, self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'product_id' on model 'hr.employee.public'

**Comment by Trivedi-Vacha-SerpentCS** [comment]
@bvanjeelharia in Local we are not able to replicate the issue, can you please send the steps here?

**Comment by bvanjeelharia** [comment]
@Trivedi-Vacha-SerpentCS , we are just trying to add timesheet for users who don't have hr.group_hr_user or higher group

**Comment by Trivedi-Vacha-SerpentCS** [comment]
[PR#26](https://github.com/onesteinbv/ProjectManagement/pull/26)
